name: rooter
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: George Lesica <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  dart_dev: ^1.7.7
  dart_style: ^1.0.7
  meta: ^1.1.1
  test: ^0.12.0
